server:
  port: 8080



spring:
  datasource:
    username: root
    password: 171605mEi
    url:
      jdbc:mysql://localhost:3306/search_engine_body_title?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #update # create-drop

      format_sql: true
      user_sql_comments: true

      show_sql: true
      generate_statistics: true
      cache:
        use_structured_entries: true


    show-sql: false

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://radiomv.ru
      name: radiomv.ru
    - url: https://dombulgakova.ru/
      name: Музей-театр Булгакова
#    - url: https://www.svetlovka.ru/
#      name: Svetlovka
#    - url: https://nikoartgallery.com/
#      name: Галерея Аганесяна 91 стр
#    - url: https://ipfran.ru/
#      name: ipfran.ru

